---
- name: Clean server blocks
  loop: "{{ server_blocks_to_delete | default([0], true) }}"
  when: item != 0
  notify: Reload NGINX
  file:
    state: absent
    path: "/etc/nginx/conf.d/{{ item }}"
