---
- name: Ensure NGINX is installed
  yum:
    name: nginx
    state: installed

# - name: Trigger NGINX start
#   command: /bin/true
#   notify: Start NGINX

- name: Ensure /etc/nginx/conf.d exists
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: Ensure /etc/nginx/default.d exists
  file:
    path: /etc/nginx/default.d
    state: directory